#######################################################################################################
#
# title:       Docker/AWS ECS Compose YAML file for spring-music
# author:      Keith Nielsen (keithnielsen68@gmail.com)
# url:         https://github.com/kniels5/spring-music-docker.git  
# description: Takes Spring-Music Docker image and pushes to ECS via ECS CLI
# to run:      ecs-cli compose --file spring-music-compose.yml up (Should work with Docker Compose)
# 
#######################################################################################################

spring-music-docker:
  image: localhost:18444/dfs/spring-music-docker:latest
  ports:
   - "8087:8080"
  user: root 
